name = "axiom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Axiom"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
linter.dupNamespace = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Axiom"
