name = "axiom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Lemma"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Lemma"
leanOptions = {linter.dupNamespace = false, linter.unusedTactic = false, linter.style.nameCheck = false, diagnostics.threshold = 1000}

[[lean_lib]]
name = "sympy"

[[lean_lib]]
name = "stdlib"