name = "axiom"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Axiom"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Axiom"
leanOptions = {linter.dupNamespace = false, linter.unusedTactic = false}

[[lean_lib]]
name = "sympy"

[[lean_lib]]
name = "std"